# Generated by Django 6.0.2 on 2026-02-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_picture', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
