from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser
import secrets
from django.utils import timezone
from datetime import timedelta

class User(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15)
    address = models.TextField(blank=True)
    state = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    pincode = models.CharField(max_length=10, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

class PasswordResetToken(models.Model):
    """
    One row = one active password reset request.

    token  : a 32-char cryptographically secure random hex string
             generated by secrets.token_hex(16).
             This is what goes in the email link URL.

    expires: 1 hour from creation. After that the token is invalid.

    We delete the row after it is used OR after it expires,
    so old tokens can never be reused.
    """
    user       = models.ForeignKey(User, on_delete=models.CASCADE)
    token      = models.CharField(max_length=128, unique=True)
    expires    = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    def is_valid(self):
        return timezone.now() < self.expires

    @classmethod
    def create_for_user(cls, user):
        # Delete any existing tokens for this user first
        cls.objects.filter(user=user).delete()
        return cls.objects.create(
            user=user,
            token=secrets.token_hex(16),
            expires=timezone.now() + timedelta(hours=1),
        )

    def __str__(self):
        return f"Reset token for {self.user.email}"
